load("//tools/build_defs:boost_build.bzl", "boost_build")

boost_build(
    name = "boost",
    boost_library = "regex",
    lib_source = "@boost//:all",
    shared_libraries = ["libboost_regex.so.1.68.0"],
)
